a=input("Student No. :")
b=input("Student Name :")
c=int(input("Marks1 :"))
d=int(input("Marks2 :"))
e=int(input("Marks3 :"))
print("---------------------------------------")
print("Student No. :",a)
print("Student Name :",b)
print("Marks1 :",c)
print("Marks2 :",d)
print("Marks3 :",e)
print("TotalMarks :",c+d+e)
print("Average :",(c+d+e)/3)

