a=int(input("Employee id_no. :"))
b=str(input("Employee Name :"))
c=float(input("Basic Salary :"))
d=float(input("HRA :"))
e=float(input("DR :"))
print("Employee id_no. :",a)
print("Employee Name",b)
print("Basic salary",c)
print("HRA",d)
print("DR",e)
print("Gross_Salary =",c+d+e)
